// generated by the CLI
import { createApp } from 'vue';
import App from './App.vue';

import HomePage from './components/HomePage.vue';

const app = createApp(App).mount('#app');
app.component('HomePage', HomePage); // This component now registered globally
// first parmeter is the name of the component or the HTML element name that i want to use to render this component in other components.
// second paremeter is the component itself

/*
Global variables inevitably cause problems because they can be hard to locate
It's easy to run into naming conflicts
Global components can lead to increased bundles sizes - global components will always be loaded even if the user never visits the part of the application where that component is used.
*/