// generated by the CLI
import { createApp } from 'vue';
import App from './App.vue';

import HomePage from './components/HomePage.vue';

const app = createApp(App).mount('#app');
app.component('HomePage', HomePage); // This component now registered globally

/*
Global variables inevitably cause problems because they can be hard to locate
It's easy to run into naming conflicts
Global components can lead to increased bundles sizes - global components will always be loaded even if the user never visits the part of the application where that component is used.
*/